/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 36
#define YY_END_OF_BUFFER 37
static yyconst short int yy_accept[248] =
    {   0,
        0,    0,   31,   31,   35,   35,   37,   27,    4,    5,
        6,    8,   27,    7,    8,    6,    7,    6,    1,    1,
        8,    7,    7,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   25,   31,   30,   28,   36,   29,   35,
       34,   36,   36,    4,    5,    0,    0,    0,   10,    0,
       26,    0,    1,    1,    9,    0,    0,    1,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   20,   24,   24,
       24,   24,   24,   24,   24,   24,   19,   24,   22,   24,
       24,   24,   24,   24,   18,   22,   24,   24,   24,   24,

       24,   24,   24,   21,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   31,   30,   35,   34,   32,   33,    2,
        0,    0,   10,    0,    0,    3,    0,    3,   23,   24,
       24,   24,   24,   24,   24,   24,   24,   17,   24,   24,
       24,   21,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   12,   11,    0,    3,   24,
       24,   24,   15,   24,   24,   20,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   21,   14,
       24,   24,   24,   16,   13,   24,   24,   24,    0,    3,

       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   22,    3,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    4,    5,    1,    1,    6,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   17,   18,   19,
       20,   21,    1,   22,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
       37,   44,   45,   46,   47,   48,   49,   50,   51,   37,
       23,   24,   25,   26,   27,    1,   28,   29,   30,   31,

       32,   33,   34,   35,   36,   37,   38,   39,   40,   41,
       42,   43,   37,   44,   45,   46,   47,   48,   49,   50,
       51,   37,   52,   53,   54,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[55] =
    {   0,
        1,    1,    2,    1,    1,    1,    3,    3,    3,    1,
        1,    1,    1,    1,    4,    4,    1,    1,    1,    1,
        1,    1,    1,    1,    5,    1,    6,    4,    4,    4,
        4,    4,    4,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    7,    8,    7
    } ;

static yyconst short int yy_base[257] =
    {   0,
        0,    0,   52,   55,   57,   60,  405,  406,  402,  400,
      406,   46,   64,  393,  406,   66,  406,  388,   59,   70,
      380,   36,  379,   43,   48,   61,   56,   73,   83,  356,
        0,   60,   31,  355,   79,   83,   89,  364,   86,   93,
       54,  367,  103,  406,    0,  391,  406,  406,  406,    0,
      390,  383,  383,  388,  386,  363,  362,  116,  380,    0,
      406,  126,  111,  133,  406,  135,  150,  148,    0,  354,
      340,  349,  340,  336,  352,  338,  330,  328,  331,  344,
      328,  334,  333,  327,  329,  323,    0,  325,  321,  337,
      324,  333,  324,  316,    0,    0,  326,  330,  317,  139,

      312,  313,  324,    0,  308,  311,   90,  321,  308,  315,
      304,  305,  312,    0,  344,    0,  343,  406,  406,  406,
      320,  128,  338,    0,  147,  157,  327,  159,    0,  314,
      305,  301,  307,  294,  292,  295,  303,    0,  302,  288,
      300,  282,  300,  287,  289,  295,  294,  291,  292,  285,
      147,  137,  280,  289,  284,  278,  286,  285,  270,  279,
      269,  274,  277,  280,  264,  303,  302,  174,  163,  256,
      265,  273,    0,  258,  257,    0,  258,  269,  272,  253,
      266,  149,  258,  260,  251,  262,  261,  248,  252,    0,
      246,  261,  247,    0,    0,  248,  254,  253,  268,  172,

      255,  240,  240,  236,  243,  238,  245,  243,  234,  225,
      242,  241,  243,  229,  238,  222,  233,  227,  176,  224,
      236,  232,  220,  229,  216,  231,  212,  221,  209,  215,
      213,  214,  211,  204,  207,  184,  184,  176,  187,  179,
      153,  142,   85,   84,   55,   53,  406,  193,  201,  209,
      214,  220,  226,  230,  235,  243
    } ;

static yyconst short int yy_def[257] =
    {   0,
      247,    1,  248,  248,  249,  249,  247,  247,  247,  247,
      247,  247,  250,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  247,  252,  247,  247,  247,  247,  253,
      247,  247,  247,  247,  247,  247,  254,  255,  247,  256,
      247,  247,  247,  247,  247,  247,  247,  247,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,

      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  252,  247,  253,  247,  247,  247,  247,
      254,  255,  247,  255,  255,  247,  247,  247,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  247,  247,  247,  247,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  247,  247,

      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  247,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  251,    0,  247,  247,  247,
      247,  247,  247,  247,  247,  247
    } ;

static yyconst short int yy_nxt[461] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   11,   16,
       17,   16,   18,   17,   19,   20,   21,   17,   22,   17,
       23,   11,   15,    8,   15,   17,    8,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   31,   31,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   42,   43,   31,
       31,   44,    8,    8,   46,   65,   65,   46,   90,   51,
       56,   57,   51,   52,   48,   53,   52,   48,   53,   59,
       62,   66,   91,   57,   57,   57,   57,   57,   57,   72,
       63,   64,   66,   70,   68,   68,   71,   60,   74,   73,
       67,   77,   87,  190,  107,   75,  246,   78,  108,   88,

       89,   67,   76,   47,   48,   49,   47,   48,   49,   48,
       82,   79,   48,   80,   93,   95,   98,  101,   83,  245,
       94,  123,   81,   66,   84,  159,   96,  103,   97,   85,
      244,  102,   99,  166,  104,  160,  105,  110,  111,  124,
       56,   57,   67,  106,  112,   66,  113,   68,   68,  126,
      126,  124,  167,   57,   57,   57,   57,   57,   57,  127,
       66,  127,   68,   68,   67,  128,  152,  189,  153,  243,
      124,  126,  126,  169,  169,  190,  187,  169,  169,   67,
      188,  154,  207,  199,   87,  199,  219,  219,  168,  200,
      219,  219,  208,   45,   45,   45,   45,   45,   45,   45,

       45,   50,   50,   50,   50,   50,   50,   50,   50,   58,
      138,   58,   58,   58,   58,   58,   58,   69,  195,   69,
      114,  242,  114,  114,  114,  114,  116,  241,  240,  116,
      116,  116,  116,  121,  121,  122,  239,  122,  122,  122,
      122,  122,  122,  125,  238,  125,  125,  125,  125,  125,
      125,   87,   95,   96,  195,  237,  236,  173,  235,  173,
      234,  233,   95,  232,  173,  231,  194,  176,  138,   96,
      230,  229,  194,  228,  227,  226,  225,  224,  223,  222,
      221,  104,  220,  200,  218,  176,  176,  217,  216,  215,
      214,  213,  212,  211,  210,  209,  190,  206,  205,  204,

      194,  203,  202,  190,  201,  195,  194,  122,  122,  198,
      173,  104,  197,  195,  196,  195,  190,  194,  176,  193,
      192,  191,  186,  185,  184,  183,  182,  181,   87,  180,
      179,   87,  178,  177,  176,  175,  174,  173,  138,  172,
      171,  170,  128,  122,  120,  117,  115,  165,  164,  163,
      162,   95,  161,  158,  157,  156,  155,   95,  151,  150,
      149,  129,  104,  129,  148,  147,  146,  145,  144,  143,
      142,  141,  140,  139,  138,  137,  136,   96,  135,  134,
      133,  132,  131,  130,  129,  125,  120,  120,   55,   54,
      119,  118,  117,  115,  109,  100,   92,   86,   65,   65,

       65,   61,   55,   54,  247,    7,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247
    } ;

static yyconst short int yy_chk[461] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,   22,   22,    4,   33,    5,
       12,   12,    6,    5,    5,    5,    6,    6,    6,   13,
       16,   19,   33,   12,   12,   12,   12,   12,   12,   25,
       16,   16,   20,   24,   20,   20,   24,   13,   26,   25,
       19,   27,   32,  246,   41,   26,  245,   27,   41,   32,

       32,   20,   26,    3,    3,    3,    4,    4,    4,    5,
       29,   28,    6,   28,   35,   36,   37,   39,   29,  244,
       35,   58,   28,   63,   29,  107,   36,   40,   36,   29,
      243,   39,   37,  122,   40,  107,   40,   43,   43,   58,
       62,   62,   63,   40,   43,   64,   43,   64,   64,   66,
       66,  122,  125,   62,   62,   62,   62,   62,   62,   67,
       68,   67,   68,   68,   64,   67,  100,  152,  100,  242,
      125,  126,  126,  128,  128,  152,  151,  169,  169,   68,
      151,  100,  182,  168,  241,  168,  200,  200,  126,  168,
      219,  219,  182,  248,  248,  248,  248,  248,  248,  248,

      248,  249,  249,  249,  249,  249,  249,  249,  249,  250,
      240,  250,  250,  250,  250,  250,  250,  251,  239,  251,
      252,  238,  252,  252,  252,  252,  253,  237,  236,  253,
      253,  253,  253,  254,  254,  255,  235,  255,  255,  255,
      255,  255,  255,  256,  234,  256,  256,  256,  256,  256,
      256,  233,  232,  231,  230,  229,  228,  227,  226,  225,
      224,  223,  222,  221,  220,  218,  217,  216,  215,  214,
      213,  212,  211,  210,  209,  208,  207,  206,  205,  204,
      203,  202,  201,  199,  198,  197,  196,  193,  192,  191,
      189,  188,  187,  186,  185,  184,  183,  181,  180,  179,

      178,  177,  175,  174,  172,  171,  170,  167,  166,  165,
      164,  163,  162,  161,  160,  159,  158,  157,  156,  155,
      154,  153,  150,  149,  148,  147,  146,  145,  144,  143,
      142,  141,  140,  139,  137,  136,  135,  134,  133,  132,
      131,  130,  127,  123,  121,  117,  115,  113,  112,  111,
      110,  109,  108,  106,  105,  103,  102,  101,   99,   98,
       97,   94,   93,   92,   91,   90,   89,   88,   86,   85,
       84,   83,   82,   81,   80,   79,   78,   77,   76,   75,
       74,   73,   72,   71,   70,   59,   57,   56,   55,   54,
       53,   52,   51,   46,   42,   38,   34,   30,   23,   21,

       18,   14,   10,    9,    7,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#define INITIAL 0
#include <stdio.h>
#include "parser.hpp"
#pragma warning(disable: 4996 6385 6011 4267 4244 4013 4312 4273 28251)
#define CANTIDAD_OPERADORES 22
#define CANTIDAD_NUMEROS 1000
#define CANTIDAD_CADENAS 1000  
#define CANTIDAD_PALABRAS_RESERVADAS 55
#define CANTIDAD_IDENTIFICADORES 1000

unsigned int columna =1;
unsigned int fila =1; 

struct palabra_reservada {
	char palabra[15] ="";
	unsigned int cantidad;
};
palabra_reservada arreglo_palabras[CANTIDAD_PALABRAS_RESERVADAS];

struct cadena_caracteres{
	char* cadena = 0; //es char* porque son muy variables las cadenas
	unsigned int cantidad = 0;
};	
cadena_caracteres arreglo_cadenas[CANTIDAD_CADENAS];

struct operadores{
	char operador[3]= {' ', ' ', '\0'};
	unsigned int cantidad = 0;
};	
operadores arreglo_operadores[CANTIDAD_OPERADORES];

/*estructura operadores contiene el operador en char[] y toma dos espacios,
esto porque hay operadores de mas de 1 caracter
Entonces hay un arreglo de estructuras, que contiene a todos los operadores y las veces que salen
*/

struct numero{
	char* constante_numerica = 0; //es char* porque son muy variables las constantes numericas
	unsigned int cantidad = 0;
};	
numero arreglo_numeros[CANTIDAD_NUMEROS];

struct identificador{
	char* cadena_identificador = 0; //es char* porque son muy variables las constantes numericas
	unsigned int cantidad = 0;
};	
identificador arreglo_identificadores[CANTIDAD_IDENTIFICADORES];

void contar_cantidad_palabra();
void contar_cantidad_cadena();
void contar_cantidad_operador();
void contar_cantidad_numero();
void contar_cantidad_identificador();

int regresar_numero_token_operador();
int regresar_numero_token_palabra();


#define COMENTARIO_LLAVE 1
#define COMENTARIO_PARENTESIS 2


/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;




	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 248 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 406 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
{
						//printf("(%d,%d) Entero: %s\n",fila,columna,yytext);
						contar_cantidad_numero();
						columna += yyleng;
						yylval.intVal = atoi(yytext);
						return DECIMAL_INT;
					}
	YY_BREAK
case 2:
YY_RULE_SETUP
{
						//printf("(%d,%d) Hexadecimal: %s\n",fila,columna,yytext);
						contar_cantidad_numero();
						columna += yyleng;
						return HEXADECIMAL;
					}
	YY_BREAK
case 3:
YY_RULE_SETUP
{
						//printf("(%d,%d) Real: %s\n",fila,columna ,yytext);
						contar_cantidad_numero();
						columna += yyleng;
						yylval.floatVal = atof(yytext);
						return REAL_DECIMAL;
					}
	YY_BREAK
case 4:
YY_RULE_SETUP
{
						//printf("(%d,%d) Espacios en blanco o tabuladores encontrados: %d\n",fila,columna,yyleng);
						columna += yyleng;
						
					}
	YY_BREAK
case 5:
YY_RULE_SETUP
{
						//printf("(%d,%d) Saltos de linea encontrados: %d\n",fila, columna,yyleng);
						fila+=yyleng;
						columna=1;
					}
	YY_BREAK
case 6:
case 7:
case 8:
YY_RULE_SETUP
{
										//printf("(%d,%d) Operador: %s\n",fila, columna,yytext);
										contar_cantidad_operador();
										columna+=yyleng;
										return *yytext;
									}
	YY_BREAK
case 9:
YY_RULE_SETUP
{
										//printf("(%d,%d) Operador: %s\n",fila, columna,yytext);
										contar_cantidad_operador();
										columna+=yyleng;
										return regresar_numero_token_operador();
									}
	YY_BREAK
case 10:
case 11:
YY_RULE_SETUP
{
								//printf("(%d,%d) Cadena Char: %s\n",fila, columna,yytext);
								contar_cantidad_cadena();
								columna+=yyleng;
								return QUOTED_CHAR;
							}
	YY_BREAK
case 12:
YY_RULE_SETUP
{
								//printf("(%d,%d) Cadena: %s\n",fila, columna,yytext);
								contar_cantidad_cadena();
								columna+=yyleng;
								return QUOTED_STRING;
							}
	YY_BREAK
case 13:
case 14:
case 15:
case 16:
case 17:
case 18:
case 19:
case 20:
case 21:
case 22:
case 23:
YY_RULE_SETUP
{
							//printf("(%d,%d) Reservada: %s\n",fila,columna,yytext);
							contar_cantidad_palabra();
							columna+=yyleng;
							return regresar_numero_token_palabra();
						}
	YY_BREAK
case 24:
YY_RULE_SETUP
{
						//printf("(%d,%d) Identificador: %s\n",fila,columna,yytext);
						contar_cantidad_identificador();
						columna+=yyleng;
						return IDENTIFIER;
					}
	YY_BREAK
case 25:
YY_RULE_SETUP
{
						//printf("(%d,%d) Comentario:",fila,columna);
						BEGIN(COMENTARIO_LLAVE);
						columna++;
					} 
	YY_BREAK
case 26:
YY_RULE_SETUP
{
						BEGIN(COMENTARIO_PARENTESIS);
						columna++;
					} 
	YY_BREAK
case 27:
YY_RULE_SETUP
{
			columna++;
		}
	YY_BREAK

case 28:
YY_RULE_SETUP
{
							//printf("No se puede abrir comentario dentro de un comentario\n");
							yyterminate();
							
						}
	YY_BREAK
case 29:
YY_RULE_SETUP
{
							puts("");
							BEGIN(INITIAL);
							columna++;
						}
	YY_BREAK
case 30:
YY_RULE_SETUP
{
						//printf("%s",yytext);
						fila+= yyleng;
						columna=1;
					}
	YY_BREAK
case 31:
YY_RULE_SETUP
{
							//printf("%s",yytext);
							columna+=yyleng;
						}
	YY_BREAK


case 32:
YY_RULE_SETUP
{
							//printf("No se puede abrir comentario dentro de un comentario\n");
							yyterminate();
							
						}
	YY_BREAK
case 33:
YY_RULE_SETUP
{
							puts("");
							BEGIN(INITIAL);
							columna++;
						}
	YY_BREAK
case 34:
YY_RULE_SETUP
{
						//printf("%s",yytext);
						fila+=yyleng;
						columna=1;
					}
	YY_BREAK
case 35:
YY_RULE_SETUP
{
							//printf("%s",yytext);
							columna+=yyleng;
						}
	YY_BREAK

case 36:
YY_RULE_SETUP
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMENTARIO_LLAVE):
case YY_STATE_EOF(COMENTARIO_PARENTESIS):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 248 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 248 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 247);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif


void contar_cantidad_palabra()
{
	for (int i = 0; i< CANTIDAD_PALABRAS_RESERVADAS; i++)
	{
		if(strcmp(arreglo_palabras[i].palabra,yytext) == 0) //si es 0 es que son iguales
			{
				arreglo_palabras[i].cantidad++;
				break;
			}
		else if (strcmp(arreglo_palabras[i].palabra,"") == 0 )
			{
				strncpy(arreglo_palabras[i].palabra, yytext, 14);
				arreglo_palabras[i].cantidad++;
				break;
				
			}
	}
}

void contar_cantidad_cadena()
{
	for (int i = 0; i< CANTIDAD_CADENAS; i++)
	{
		if(arreglo_cadenas[i].cadena)
			if(strcmp(arreglo_cadenas[i].cadena,yytext) == 0) //si es 0 es que son iguales
			{
				arreglo_cadenas[i].cantidad++;
				break;
			}
			else
				continue;
		else
		{
			arreglo_cadenas[i].cadena = (char*) malloc((yyleng+1) * sizeof(char));
			if(arreglo_cadenas[i].cadena)
			{
				strcpy(arreglo_cadenas[i].cadena, yytext);
				arreglo_cadenas[i].cantidad++;
			}
				
			break;
		}
	}
}

void contar_cantidad_operador()
{
	/* primero checa si existe el operador en alguna estructura del arreglo, si si le suma a la cantidad
	de lo contrario sobreescribe uno vacio para poner el operador*/
	for (int i = 0; i< CANTIDAD_OPERADORES; i++)
	{
		if(strcmp(arreglo_operadores[i].operador,yytext) == 0) //si es 0 es que son iguales
			{
				arreglo_operadores[i].cantidad++;
				break;
			}
		else if (strcmp(arreglo_operadores[i].operador,"  ") == 0 )
			{
				strncpy(arreglo_operadores[i].operador, yytext, 2);
				arreglo_operadores[i].cantidad++;
				break;
				
			}
		

	}

}

void contar_cantidad_numero()
{
	for (int i = 0; i< CANTIDAD_NUMEROS; i++)
	{
		if(arreglo_numeros[i].constante_numerica)
			if(strcmp(arreglo_numeros[i].constante_numerica,yytext) == 0) //si es 0 es que son iguales
			{
				arreglo_numeros[i].cantidad++;
				break;
			}
			else
				continue;
		else
		{
			arreglo_numeros[i].constante_numerica = (char*) malloc((yyleng+1) * sizeof(char));
			if(arreglo_numeros[i].constante_numerica)
			{
				strcpy(arreglo_numeros[i].constante_numerica, yytext);
				arreglo_numeros[i].cantidad++;
			}
				
			break;
		}
	}
}

void contar_cantidad_identificador()
{
	for (int i = 0; i< CANTIDAD_IDENTIFICADORES; i++)
	{
		if(arreglo_identificadores[i].cadena_identificador)
			if(strcmp(arreglo_identificadores[i].cadena_identificador,yytext) == 0) //si es 0 es que son iguales
			{
				arreglo_identificadores[i].cantidad++;
				break;
			}
			else
				continue;
		else
		{
			arreglo_identificadores[i].cadena_identificador = (char*) malloc((yyleng+1) * sizeof(char));
			if(arreglo_identificadores[i].cadena_identificador)
			{
				strcpy(arreglo_identificadores[i].cadena_identificador, yytext);
				arreglo_identificadores[i].cantidad++;
			}
				
			break;
		}
	}
}
int regresar_numero_token_operador()
{
	if (strcmp(yytext, ":=") == 0) return ASSIGN;
	else if (strcmp(yytext, "..") == 0) return SUBRANGE;
	else if (strcmp(yytext, "<>") == 0) return NOTEQUAL;
	else if (strcmp(yytext, "<=") == 0) return LE;
	else if (strcmp(yytext, ">=") == 0) return RE;
	return 0;
}
int regresar_numero_token_palabra()
{
	char* lowercase_yytext = strdup(yytext);
	for (int i = 0; lowercase_yytext[i]; i++) {
    	lowercase_yytext[i] = tolower(lowercase_yytext[i]);
	}
	if (strcmp(lowercase_yytext, "program") == 0) { free(lowercase_yytext); return PROGRAM_TOKEN;}
	else if (strcmp(lowercase_yytext, "begin") == 0) { free(lowercase_yytext); return BEGIN_TOKEN;}
	else if (strcmp(lowercase_yytext, "uses") == 0) { free(lowercase_yytext); return USES_TOKEN;}
	else if (strcmp(lowercase_yytext, "unit") == 0) { free(lowercase_yytext); return UNIT_TOKEN;}
	else if (strcmp(lowercase_yytext, "interface") == 0) { free(lowercase_yytext); return INTERFACE_TOKEN;}

	else if (strcmp(lowercase_yytext, "implementation") == 0) { free(lowercase_yytext); return IMPLEMENTATION_TOKEN;}
	else if (strcmp(lowercase_yytext, "label") == 0) { free(lowercase_yytext); return LABEL_TOKEN;}
	else if (strcmp(lowercase_yytext, "const") == 0) { free(lowercase_yytext); return CONST_TOKEN;}
	else if (strcmp(lowercase_yytext, "type") == 0) { free(lowercase_yytext); return TYPE_TOKEN;}
	else if (strcmp(lowercase_yytext, "real") == 0) { free(lowercase_yytext); return REAL_TOKEN;}

	else if (strcmp(lowercase_yytext, "integer") == 0) { free(lowercase_yytext); return INTEGER_TOKEN;}
	else if (strcmp(lowercase_yytext, "longint") == 0) { free(lowercase_yytext); return LONGINT_TOKEN;}
	else if (strcmp(lowercase_yytext, "word") == 0) { free(lowercase_yytext); return WORD_TOKEN;}
	else if (strcmp(lowercase_yytext, "char") == 0) { free(lowercase_yytext); return CHAR_TOKEN;}
	else if (strcmp(lowercase_yytext, "boolean") == 0) { free(lowercase_yytext); return BOOLEAN_TOKEN;}

	else if (strcmp(lowercase_yytext, "true") == 0) { free(lowercase_yytext); return TRUE_TOKEN;}
	else if (strcmp(lowercase_yytext, "false") == 0) { free(lowercase_yytext); return FALSE_TOKEN;}
	else if (strcmp(lowercase_yytext, "string") == 0) { free(lowercase_yytext); return STRING_TOKEN;}
	else if (strcmp(lowercase_yytext, "packed") == 0) { free(lowercase_yytext); return PACKED_TOKEN;}
	else if (strcmp(lowercase_yytext, "array") == 0) { free(lowercase_yytext); return ARRAY_TOKEN;}

	else if (strcmp(lowercase_yytext, "record") == 0) { free(lowercase_yytext); return RECORD_TOKEN;}
	else if (strcmp(lowercase_yytext, "end") == 0) { free(lowercase_yytext); return END_TOKEN;}
	else if (strcmp(lowercase_yytext, "case") == 0) { free(lowercase_yytext); return CASE_TOKEN;}
	else if (strcmp(lowercase_yytext, "otherwise") == 0) { free(lowercase_yytext); return OTHERWISE_TOKEN;}
	else if (strcmp(lowercase_yytext, "of") == 0) { free(lowercase_yytext); return OF_TOKEN;}

	else if (strcmp(lowercase_yytext, "set") == 0) { free(lowercase_yytext); return SET_TOKEN;}
	else if (strcmp(lowercase_yytext, "var") == 0) { free(lowercase_yytext); return VAR_TOKEN;}
	else if (strcmp(lowercase_yytext, "forward") == 0) { free(lowercase_yytext); return FORWARD_TOKEN;}
	else if (strcmp(lowercase_yytext, "external") == 0) { free(lowercase_yytext); return EXTERNAL_TOKEN;}
	else if (strcmp(lowercase_yytext, "function") == 0) { free(lowercase_yytext); return FUNCTION_TOKEN;}
	
	else if (strcmp(lowercase_yytext, "procedure") == 0) { free(lowercase_yytext); return PROCEDURE_TOKEN;}
	else if (strcmp(lowercase_yytext, "file") == 0) { free(lowercase_yytext); return FILE_TOKEN;}
	else if (strcmp(lowercase_yytext, "goto") == 0) { free(lowercase_yytext); return GOTO_TOKEN;}
	else if (strcmp(lowercase_yytext, "if") == 0) { free(lowercase_yytext); return IF_TOKEN;}
	else if (strcmp(lowercase_yytext, "then") == 0) { free(lowercase_yytext); return THEN_TOKEN;}

	else if (strcmp(lowercase_yytext, "else") == 0) { free(lowercase_yytext); return ELSE_TOKEN;}
	else if (strcmp(lowercase_yytext, "repeat") == 0) { free(lowercase_yytext); return REPEAT_TOKEN;}
	else if (strcmp(lowercase_yytext, "until") == 0) { free(lowercase_yytext); return UNTIL_TOKEN;}
	else if (strcmp(lowercase_yytext, "while") == 0) { free(lowercase_yytext); return WHILE_TOKEN;}
	else if (strcmp(lowercase_yytext, "do") == 0) { free(lowercase_yytext); return DO_TOKEN;}

	else if (strcmp(lowercase_yytext, "for") == 0) { free(lowercase_yytext); return FOR_TOKEN;}
	else if (strcmp(lowercase_yytext, "to") == 0) { free(lowercase_yytext); return TO_TOKEN;}
	else if (strcmp(lowercase_yytext, "downto") == 0) { free(lowercase_yytext); return DOWNTO_TOKEN;}
	else if (strcmp(lowercase_yytext, "with") == 0) { free(lowercase_yytext); return WITH_TOKEN;}
	else if (strcmp(lowercase_yytext, "nil") == 0) { free(lowercase_yytext); return NIL_TOKEN;}

	else if (strcmp(lowercase_yytext, "read") == 0) { free(lowercase_yytext); return READ_TOKEN;}
	else if (strcmp(lowercase_yytext, "readln") == 0) { free(lowercase_yytext); return READLN_TOKEN;}
	else if (strcmp(lowercase_yytext, "write") == 0) { free(lowercase_yytext); return WRITE_TOKEN;}
	else if (strcmp(lowercase_yytext, "writeln") == 0) { free(lowercase_yytext); return WRITELN_TOKEN;}
	else if (strcmp(lowercase_yytext, "in") == 0) { free(lowercase_yytext); return IN_TOKEN;}

	else if (strcmp(lowercase_yytext, "or") == 0) { free(lowercase_yytext); return OR_TOKEN;}
	else if (strcmp(lowercase_yytext, "div") == 0) { free(lowercase_yytext); return DIV_TOKEN;}
	else if (strcmp(lowercase_yytext, "mod") == 0) { free(lowercase_yytext); return MOD_TOKEN;}
	else if (strcmp(lowercase_yytext, "and") == 0) { free(lowercase_yytext); return AND_TOKEN;}
	else if (strcmp(lowercase_yytext, "not") == 0) { free(lowercase_yytext); return NOT_TOKEN;}
	return 0;
}

int yywrap(void) 
{
	FILE * palabras_reservadas = fopen("palabras_reservadas.csv", "wt");
	if (!palabras_reservadas)
		printf("No se pudo abrir el archivo de palabras_reservadas");
	else
	{
		for(int i = 0; i < CANTIDAD_OPERADORES; i++)
			if(strcmp(arreglo_palabras[i].palabra,"") == 0)
				continue;
			else
				fprintf(palabras_reservadas,"%d,%s,%d\n",i,arreglo_palabras[i].palabra,arreglo_palabras[i].cantidad);
		fclose(palabras_reservadas);
	}
	
	FILE* constantes_cadenas = fopen("constantes_cadenas.csv", "wt");
	if (!constantes_cadenas)
	    printf("No se pudo abrir el archivo de constantes_cadenas");
	else 
	{
	    for (int i = 0; i < CANTIDAD_CADENAS; i++)
		if(arreglo_cadenas[i].cadena)
		{
	        fprintf(constantes_cadenas, "%d,%s,%d\n", i, arreglo_cadenas[i].cadena, arreglo_cadenas[i].cantidad);
			free(arreglo_cadenas[i].cadena);
		}
		else
			break;
		fclose(constantes_cadenas);
	}
	
	FILE * caracteres_especiales = fopen("caracteres_especiales.csv", "wt");
	if (!caracteres_especiales)
		printf("No se pudo abrir el archivo de caracteres_especiales");
	else
	{
		for(int i = 0; i < CANTIDAD_OPERADORES; i++)
			if(strcmp(arreglo_operadores[i].operador,"  ") == 0)
				continue;
			else
				if(strcmp(arreglo_operadores[i].operador,",") ==0)
					fprintf(caracteres_especiales,"%d,%s,%d\n",i,"comma",arreglo_operadores[i].cantidad);
				else
					fprintf(caracteres_especiales,"%d,%s,%d\n",i,arreglo_operadores[i].operador,arreglo_operadores[i].cantidad);
		fclose(caracteres_especiales);
	}
	FILE * constantes_numericas = fopen("constantes_numericas.csv", "wt");
	if (!constantes_numericas)
		printf("No se pudo abrir el archivo de constantes_numericas");
	else
	{
		for(int i = 0; i < CANTIDAD_NUMEROS; i++)
		if(arreglo_numeros[i].constante_numerica)
		{
			fprintf(constantes_numericas,"%d,%s,%d\n",i,arreglo_numeros[i].constante_numerica,arreglo_numeros[i].cantidad);
			free(arreglo_numeros[i].constante_numerica);
		}
		else
			break;
		fclose(constantes_numericas);
	}
	FILE * identificadores = fopen("identificadores.csv", "wt");
	if (!identificadores)
		printf("No se pudo abrir el archivo de identificadores");
	else
	{
		for(int i = 0; i < CANTIDAD_IDENTIFICADORES; i++)
		if(arreglo_identificadores[i].cadena_identificador)
		{
			fprintf(identificadores,"%d,%s,%d\n",i,arreglo_identificadores[i].cadena_identificador,arreglo_identificadores[i].cantidad);
			free(arreglo_identificadores[i].cadena_identificador);
		}
		else
			break;
		fclose(identificadores);
	}
   return 1;
}


/*
int main(int argc, char * argv[])
{
	char archivo_abierto = 0;
	if (argc > 1)
	{
		++argv; //apunta al siguiente elemento del arreglo
		yyin = fopen(argv[0], "rt");
		archivo_abierto = 1;
		if (!yyin)
		{
			printf("Archivo %s no puede ser abierto. Entrada tradicional.\n", argv[0]);
			yyin = stdin;
			archivo_abierto = 0;
		}		
	}
	
	yylex();
	if(archivo_abierto)
		fclose(yyin);

}*/