{************************************************}
{                                                }
{ Overlay Demo Unit                              }
{ Copyright (c) 1985,90 by Borland International }
{                                                }
{************************************************}

{$O+,F+}
unit OvrDemo1;
{ This unit is used by OVRDEMO.PAS }

interface

procedure Write1;

forward;

implementation

procedure Write1;
begin

end;

end.